[colors.bright]
black = "#555555"
blue = "#5555FF"
cyan = "#55FFFF"
green = "#55FF55"
magenta = "#FF55FF"
red = "#FF5555"
white = "#FFFFFF"
yellow = "#FFFF55"

[colors.normal]
black = "#000000"
blue = "#5555FF"
cyan = "#55FFFF"
green = "#55FF55"
magenta = "#FF55FF"
red = "#FF5555"
white = "#BBBBBB"
yellow = "#FFFF55"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "NotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "NotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "NotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "NotoMono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[window]
opacity = 0.8

[window.padding]
x = 8
y = 8
