[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "GeistMono NFP"
style = "Bold"

[font.bold_italic]
family = "GeistMono NFP"
style = "Bold Italic"

[font.italic]
family = "GeistMono NFP"
style = "Italic"

[font.normal]
family = "GeistMono NFP"
style = "Regular"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[window]
opacity = 0.8

[window.padding]
x = 8
y = 8


[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
